### ISSUE TITLE
How do i actually use this? 

### ISSUE THREAD

**Issue by 7ud** [mayTermux/awesomeshot#2]
What the title says

**Comment by nihsx** [comment]
> What the title says

Sorry, I'm currently making the docs [here](https://github.com/mayTermux/awesomeshot/wiki)

**Comment by 7ud** [comment]
Oh ok, if possible could you notify me when you have finished them?

**Comment by nihsx** [comment]
> Oh ok, if possible could you notify me when you have finished them?

Hi, now the wiki documentation is complete (though not very good). Now you can check it [here](https://github.com/mayTermux/awesomeshot/wiki), if you have any questions or difficulties use, feel free to discuss it here

**Comment by 7ud** [comment]
Thanks a lot!

**Comment by 7ud** [comment]
The main part I'm confused with is how to actually take a screen shot using it. Would it be possible for you to tell me how?

**Comment by nihsx** [comment]
> The main part I'm confused with is how to actually take a screen shot using it. Would it be possible for you to tell me how?

## How Awesomeshot work on an argument `-a` or `--auto`?

- Run awesomeshot with argument `-a` or `--auto`
- Take a screenshot
- The `inotify-tools` package will detect new files from the folder already set in config `awesomeshot.conf`
- After detecting new files, awesomeshot will edit the image with package `ImageMagick`

## What should be prepared?

1. You must check the screenshot PATH result when your phone takes a screenshot (default config `awesomeshot.conf` is `/sdcard/Pictures/Screenshots`) which is my default screenshot PATH result when taking a screenshot. **If not same, you have to change the value from variable `screenshot_result_path` on your config**

2. After the value from variable `screenshot_result_path` same with your screenshot PATH result, now run awesomeshot with argument `-a` or `--auto` and it will make `Awesomeshot` in listening mode `waiting to take screenshot`.

3. When awesomeshot on mode auto, now you can take screenshot picture and then awesomeshot will automatically detect new file on you screenshot PATH result and edit your image with `ImageMagick`

## How Awesomeshot work on an argument `-m` or `--manual`?

> Basically same with argument `-a` or `--auto` but in this argument, you have to set the PATH from a specific image, in this argument we don't need the inotify-tools package because we set the PATH specifically and manually

- Take a screenshot, or already have the image file
- Run awesomeshot with argument `-m` or `--manual` with **PATH the image file**, example:
```bash
awesomeshot -m /sdcard/Download/test.png
```
- awesomeshot will edit the image with package `ImageMagick`

**Comment by 7ud** [comment]
So simply if I run the command awesomeshot -a and then take a screen shot it will be edited (complying to my config) and saved in sdcard/Pictures/Screenshots?

**Comment by nihsx** [comment]
> So simply if I run the command awesomeshot -a and then take a screen shot it will be edited (complying to my config) and saved in sdcard/Pictures/Screenshots?

Depending on your phone when take screenshot
- https://github.com/mayTermux/awesomeshot/wiki/Customizing-Config-File#screenshot-result-path

**Comment by 7ud** [comment]
So I've read that page and my screenshot dir is `Internal storage/DCIM/Screenshots` however when setting this as my screenshot result path it doesn't seem to show in that directory and when i take a screenshot it doesn't automatically edit it after I've ran the command awesomeshot -a, any help?

**Comment by 7ud** [comment]
Still facing this issue btw, currently just using manual.

**Comment by nihsx** [comment]
> So I've read that page and my screenshot dir is `Internal storage/DCIM/Screenshots` however when setting this as my screenshot result path it doesn't seem to show in that directory and when i take a screenshot it doesn't automatically edit it after I've ran the command awesomeshot -a, any help?

**btw, I've been very busy these past few weeks so it's a bit slow to respond**

If your screenshot dir is `Internal storage/DCIM/Screenshot` you must set or change variable value `screenshot_result_path`, change:

`/sdcard/Pictures/Screenshots`

to

`/sdcard/DCIM/Screenshots`

> **NOTE: You must give permission to Termux for access your storage by command `termux-setup-storage`**

**Comment by 7ud** [comment]
Oh ok I'll give that a shot thanks alot

**Comment by 7ud** [comment]
So I've followed your steps and when I take a screenshot after using the command `awesomeshot -a` , I face this error:
```
[+] CONVERTING EXTENSION IMAGE
       [+] Convert .jpg To .png .............convert: unable to open image '/sdcard/DCIM/Screenshots/.pending-1647033100-Screenshot_20220304-211139_Termux.jpg': No such file or directory @ error/blob.c/OpenBlob/3527.
convert: no images defined `/sdcard/DCIM/Screenshots/.pending-1647033100-Screenshot_20220304-211139_Termux.png' @ error/convert.c/ConvertImageCommand/3322.
rm: cannot remove '/sdcard/DCIM/Screenshots/.pending-1647033100-Screenshot_20220304-211139_Termux.jpg': No such file or directory
 

   [+] BACKUP
cp: cannot stat '/sdcard/DCIM/Screenshots/.pending-1647033100-Screenshot_20220304-211139_Termux.png': No such file or directory
       [+] Backup File ...................... 

   [+] EDTING IMAGE
       [+] Set Rounded Corner ...............convert: unable to open image '/sdcard/DCIM/Screenshots/.pending-1647033100-Screenshot_20220304-211139_Termux.png': No such file or directory @ error/blob.c/OpenBlob/3527.
convert: image sequence is required `+clone' @ error/convert.c/ConvertImageCommand/1013.
 
       [+] Set Image Shadow .................convert: unable to open image '/sdcard/DCIM/Screenshots/.pending-1647033100-Screenshot_20220304-211139_Termux.png': No such file or directory @ error/blob.c/OpenBlob/3527.
convert: image sequence is required `+clone' @ error/convert.c/ConvertImageCommand/1013.
 
       [+] Set Image Border Color ...........convert: unable to open image '/sdcard/DCIM/Screenshots/.pending-1647033100-Screenshot_20220304-211139_Termux.png': No such file or directory @ error/blob.c/OpenBlob/3527.
convert: no images defined `/sdcard/DCIM/Screenshots/.pending-1647033100-Screenshot_20220304-211139_Termux.png' @ error/convert.c/ConvertImageCommand/3322.
 
       [+] Set Image Footer..................convert: unable to open image '/sdcard/DCIM/Screenshots/.pending-1647033100-Screenshot_20220304-211139_Termux.png': No such file or directory @ error/blob.c/OpenBlob/3527.
convert: no images defined `/sdcard/DCIM/Screenshots/.pending-1647033100-Screenshot_20220304-211139_Termux.png' @ error/convert.c/ConvertImageCommand/3322.
 
```
Any idea why this may be?

**Comment by nihsx** [comment]
I have no idea, the error is like my friend who tried it with the name of the screenshot result with the `.pending` prefix. If you understand about bash scripting maybe you can change or modify the awesomeshot script, for example removing the `.pending` prefix before converting it to PNG and etc.

**Comment by MADEWGN** [comment]
> So I've followed your steps and when I take a screenshot after using the command `awesomeshot -a` , I face this error:
> 
> ```
> [+] CONVERTING EXTENSION IMAGE
>        [+] Convert .jpg To .png .............convert: unable to open image '/sdcard/DCIM/Screenshots/.pending-1647033100-Screenshot_20220304-211139_Termux.jpg': No such file or directory @ error/blob.c/OpenBlob/3527.
> convert: no images defined `/sdcard/DCIM/Screenshots/.pending-1647033100-Screenshot_20220304-211139_Termux.png' @ error/convert.c/ConvertImageCommand/3322.
> rm: cannot remove '/sdcard/DCIM/Screenshots/.pending-1647033100-Screenshot_20220304-211139_Termux.jpg': No such file or directory
>  
> 
>    [+] BACKUP
> cp: cannot stat '/sdcard/DCIM/Screenshots/.pending-1647033100-Screenshot_20220304-211139_Termux.png': No such file or directory
>        [+] Backup File ...................... 
> 
>    [+] EDTING IMAGE
>        [+] Set Rounded Corner ...............convert: unable to open image '/sdcard/DCIM/Screenshots/.pending-1647033100-Screenshot_20220304-211139_Termux.png': No such file or directory @ error/blob.c/OpenBlob/3527.
> convert: image sequence is required `+clone' @ error/convert.c/ConvertImageCommand/1013.
>  
>        [+] Set Image Shadow .................convert: unable to open image '/sdcard/DCIM/Screenshots/.pending-1647033100-Screenshot_20220304-211139_Termux.png': No such file or directory @ error/blob.c/OpenBlob/3527.
> convert: image sequence is required `+clone' @ error/convert.c/ConvertImageCommand/1013.
>  
>        [+] Set Image Border Color ...........convert: unable to open image '/sdcard/DCIM/Screenshots/.pending-1647033100-Screenshot_20220304-211139_Termux.png': No such file or directory @ error/blob.c/OpenBlob/3527.
> convert: no images defined `/sdcard/DCIM/Screenshots/.pending-1647033100-Screenshot_20220304-211139_Termux.png' @ error/convert.c/ConvertImageCommand/3322.
>  
>        [+] Set Image Footer..................convert: unable to open image '/sdcard/DCIM/Screenshots/.pending-1647033100-Screenshot_20220304-211139_Termux.png': No such file or directory @ error/blob.c/OpenBlob/3527.
> convert: no images defined `/sdcard/DCIM/Screenshots/.pending-1647033100-Screenshot_20220304-211139_Termux.png' @ error/convert.c/ConvertImageCommand/3322.
>  
> ```
> 
> Any idea why this may be?

I also experienced the same thing, I used the code below to fix it

```python

#awesomeshot.py
import glob
import os

list_of_files = glob.glob('/sdcard/DCIM/Screenshots/*') 
latest_file = max(list_of_files, key=os.path.getctime)
a = "awesomeshot -m "
c = f'{a}{latest_file}'
os.system(c)
```

I know it doesn't work like auto mode, but it can make your job easier :)

**Comment by nihsx** [comment]
> So I've followed your steps and when I take a screenshot after using the command `awesomeshot -a` , I face this error:
> 
> ```
> [+] CONVERTING EXTENSION IMAGE
>        [+] Convert .jpg To .png .............convert: unable to open image '/sdcard/DCIM/Screenshots/.pending-1647033100-Screenshot_20220304-211139_Termux.jpg': No such file or directory @ error/blob.c/OpenBlob/3527.
> convert: no images defined `/sdcard/DCIM/Screenshots/.pending-1647033100-Screenshot_20220304-211139_Termux.png' @ error/convert.c/ConvertImageCommand/3322.
> rm: cannot remove '/sdcard/DCIM/Screenshots/.pending-1647033100-Screenshot_20220304-211139_Termux.jpg': No such file or directory
>  
> 
>    [+] BACKUP
> cp: cannot stat '/sdcard/DCIM/Screenshots/.pending-1647033100-Screenshot_20220304-211139_Termux.png': No such file or directory
>        [+] Backup File ...................... 
> 
>    [+] EDTING IMAGE
>        [+] Set Rounded Corner ...............convert: unable to open image '/sdcard/DCIM/Screenshots/.pending-1647033100-Screenshot_20220304-211139_Termux.png': No such file or directory @ error/blob.c/OpenBlob/3527.
> convert: image sequence is required `+clone' @ error/convert.c/ConvertImageCommand/1013.
>  
>        [+] Set Image Shadow .................convert: unable to open image '/sdcard/DCIM/Screenshots/.pending-1647033100-Screenshot_20220304-211139_Termux.png': No such file or directory @ error/blob.c/OpenBlob/3527.
> convert: image sequence is required `+clone' @ error/convert.c/ConvertImageCommand/1013.
>  
>        [+] Set Image Border Color ...........convert: unable to open image '/sdcard/DCIM/Screenshots/.pending-1647033100-Screenshot_20220304-211139_Termux.png': No such file or directory @ error/blob.c/OpenBlob/3527.
> convert: no images defined `/sdcard/DCIM/Screenshots/.pending-1647033100-Screenshot_20220304-211139_Termux.png' @ error/convert.c/ConvertImageCommand/3322.
>  
>        [+] Set Image Footer..................convert: unable to open image '/sdcard/DCIM/Screenshots/.pending-1647033100-Screenshot_20220304-211139_Termux.png': No such file or directory @ error/blob.c/OpenBlob/3527.
> convert: no images defined `/sdcard/DCIM/Screenshots/.pending-1647033100-Screenshot_20220304-211139_Termux.png' @ error/convert.c/ConvertImageCommand/3322.
>  
> ```
> 
> Any idea why this may be?

Hi, I fixed a bug with `.pending` prefix filename in version [1.0.5](https://github.com/mayTermux/awesomeshot/releases/tag/v.1.0.5), can you try it?
